name: Publish rocket-chip on Sonatype snapshots
'on':
  push:
    branches:
      - main
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:
    inputs:
      rcHash:
        description: 'Hash of rocket-chip commit to publish, default = empty = publish HEAD of master'
        required: true
        default: ''
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.17
      - name: Clone rocket-chip
        run: git clone https://github.com/chipsalliance/rocket-chip.git
      - uses: jodersky/setup-mill@master
        with:
          mill-version: 0.11.1
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - run: ./publish ${{ github.event.inputs.rcHash }}
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
